import "./globals.css";

import type { Metadata } from "next";
import { ttNorms } from "@/features/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ttNorms.className} antialiased`}>{children}</body>
    </html>
  );
}
