import "./globals.css";

import type { Metadata } from "next";
import { PreloaderProvider } from "@/shared/contexts/PreloaderContext";
import { ttNorms } from "@/features/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ttNorms.className} antialiased`}>
        <PreloaderProvider>{children}</PreloaderProvider>
      </body>
    </html>
  );
}
